spring:
  application:
    name: subscription-billing-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/subscription_billing}
    username: ${SPRING_DATASOURCE_USERNAME:billing}
    password: ${SPRING_DATASOURCE_PASSWORD:billing}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  info:
    env:
      enabled: true

info:
  app:
    name: Subscription Billing API
    description: Portfolio backend for a SaaS subscription billing domain
    version: ${APP_VERSION:0.0.1-SNAPSHOT}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
